XANO_AUTH_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:X3MV-cHe"
XANO_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:X3MV-cHe"
XANO_EVENT_LOGS_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:640_wGzU"
XANO_MEMBERS_ACCOUNTS_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:UnGtERdd"
XANO_SUBJECTS_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:UnGtERdd"
XANO_TASKS_BASE_URL = "https://x8ki-letl-twmt.n7.xano.io/api:UnGtERdd"
